public class Query 
{
	//The id
	private String qId;
	
	//Null if query generated by this peer, otherwise the socket that sent the query
	private PeerId source;
	
	//type
	private char type;
	
	
	//query string
	private String message;
	
	public Query(String queryId, PeerId sock, char type, String data)
	{
		qId = queryId;
		source = sock;
		message = data;
		this.type = type;
	}
	
	public boolean equals(Query other)
	{
		if(qId.equals(other.getId()))
		{
			return true;
		}
		
		else
		{
			return false;
		}
	}
	
	public boolean equals(String id)
	{
		if(qId.equals(id))
		{
			return true;
		}
		
		else
		{
			return false;
		}
	}
	
	public char getType()
	{
		return type;
	}
	
	public PeerId getSource()
	{
		return source;
	}
	
	public String getId()
	{
		return qId;
	}
	
	public String getMessage()
	{
		return message;
	}
	
	public String toString()
	{
		if(type == 'R')
		{
			return "R:(" + qId + ");" + message;
		}
		else if(type == 'Q')
		{
			return "Q:(" + qId + ");(" + message + ")";
		}
		else
		{
			return "H";
		}
	}
}
